### ISSUE TITLE
Invoking inode.Parent() in Deletable() causes deadlock

### ISSUE THREAD

**Issue by kaoet** [hanwen/go-fuse#200]
The code to reproduce:

```go
package main

import (
	"github.com/hanwen/go-fuse/fuse"
	"github.com/hanwen/go-fuse/fuse/nodefs"
)

var (
	root nodefs.Node
	file *FileNode
)
func main() {
	root = nodefs.NewDefaultNode()
	file = &FileNode{nodefs.NewDefaultNode()}

	s, _, err := nodefs.MountRoot("mnt", root, &nodefs.Options{
		Debug:      true,
	})
	if err !=nil {
		panic(err)
	}

	go func() {
		if err:= s.WaitMount(); err!=nil {
			panic(err)
		}
		root.Inode().NewChild("hello.txt", false, &FileNode{nodefs.NewDefaultNode()})
	}()

	s.Serve()
}

type FileNode struct {
	nodefs.Node
}

func (n *FileNode) Deletable() bool {
	n.Inode().Parent()
	return false
}

func (n *FileNode) Open(flags uint32, context *fuse.Context) (file nodefs.File, code fuse.Status) {
	return nodefs.NewDataFile([]byte("hello world")), fuse.OK
}
```

Then run:
```
$ ./reproduce &
$ cat mnt/hello.txt
$ umount mnt
```

The program will crash with:
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4200bc344)
	/usr/local/Cellar/go/1.9.1/libexec/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc4200bc338)
	/usr/local/Cellar/go/1.9.1/libexec/src/sync/rwmutex.go:50 +0x49
github.com/hanwen/go-fuse/fuse/nodefs.(*Inode).Parent(0xc420086300, 0x0, 0x0, 0x0)
	/go/src/github.com/hanwen/go-fuse/fuse/nodefs/inode.go:93 +0x70
main.(*FileNode).Deletable(0xc42000e430, 0x3)
```

**Comment by hanwen** [comment]
yes, don't do that.
