### ISSUE TITLE
Issue while mounting tar.gz

### ISSUE THREAD

**Issue by hanneslehmann** [hanwen/go-fuse#286]
I am using the example 'go-fuse/example/zipfs/' and calling following command:
```
➜  ls-la                                  
-rw-r--r-- 1 user users 2,1M  4. Apr 16:08 alpinefs.tar.gz
-rw-r--r-- 1 user users 1,9K  4. Apr 16:07 main.go
drwxr-xr-x 2 user users 4,0K  4. Apr 10:04 mnt
➜  go run main.go ./mnt alpinefs.tar.gz
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x50795f]

goroutine 1 [running]:
github.com/hanwen/go-fuse/nodefs.(*Inode).GetChild(0x0, 0xc0000aad44, 0x3, 0x0)
        /home/user/.gvm/pkgsets/go1.12/global/src/github.com/hanwen/go-fuse/nodefs/inode.go:408 +0x2f
github.com/hanwen/go-fuse/zipfs.(*tarRoot).OnAdd(0xc000108000, 0x5ad540, 0xc0000aa010)
        /home/user/.gvm/pkgsets/go1.12/global/src/github.com/hanwen/go-fuse/zipfs/tarfs.go:96 +0x54e
github.com/hanwen/go-fuse/nodefs.NewNodeFS(0x5ac220, 0xc000108000, 0xc0000ce0a0, 0x5ac220, 0xc000108000)
        /home/user/.gvm/pkgsets/go1.12/global/src/github.com/hanwen/go-fuse/nodefs/bridge.go:203 +0x316
github.com/hanwen/go-fuse/nodefs.Mount(0x7ffd27ce0595, 0x5, 0x5ac220, 0xc000108000, 0xc0000ce0a0, 0x0, 0xc0000aabe0, 0xc000096740)
        /home/user/.gvm/pkgsets/go1.12/global/src/github.com/hanwen/go-fuse/nodefs/mount.go:26 +0x5d
main.main()
        /home/user/Development/go/fuse/main.go:63 +0x480
exit status 2
➜  go version
go version go1.12 linux/amd64 
```

**Comment by hanwen** [comment]
what version of go-fuse do you use? I think you need to update.

**Comment by hanneslehmann** [comment]
Hi, thanks for quick response and you're right, now it mounts without the error. But, the mount is not correct: dates are wrong, the file count is wrong, there is some access issue and the directory is incomplete:

This is what I get
```
➜  mnt ls -la
total 0
drwxr-xr-x 0 root root 0  1. Jan 1970  bin
drwxr-xr-x 0 root root 0  1. Jan 1970  etc
drwxr-xr-x 0 root root 0  1. Jan 1970  lib
drwxr-xr-x 0 root root 0  1. Jan 1970  sbin
drwxr-xr-x 0 root root 0  1. Jan 1970  usr
drwxr-xr-x 0 root root 0  1. Jan 1970  var
```

this is what's inside the file:
```
➜  unflated ls -la
total 56
drwxr-xr-x 14 user users 4096 27. Mär 11:16 .
drwxr-xr-x  4 user users 4096  6. Apr 20:55 ..
drwxr-xr-x  2 user users 4096 27. Mär 11:16 bin
drwxr-xr-x  2 user users 4096 27. Mär 11:16 dev
drwxr-xr-x 15 user users 4096 27. Mär 11:16 etc
drwxr-xr-x  4 user users 4096 27. Mär 11:16 lib
dr-xr-xr-x  2 user users 4096 27. Mär 11:16 proc
drwx------  2 user users 4096 27. Mär 11:16 root
drwxr-xr-x  2 user users 4096 27. Mär 11:16 run
drwxr-xr-x  2 user users 4096 27. Mär 11:16 sbin
drwxr-xr-x  2 user users 4096 27. Mär 11:16 sys
drwxr-xr-x  2 user users 4096 27. Mär 11:16 tmp
drwxr-xr-x  6 user users 4096 27. Mär 11:16 usr
drwxr-xr-x 11 user users 4096 27. Mär 11:16 var
```

Access issue:
```
➜  mnt sudo ls -la
ls: Öffnen von Verzeichnis '.' nicht möglich: Keine Berechtigung
```

The content of the existing files however seems to be ok

**Comment by hanwen** [comment]
can you tell me where to get this file alpinefs.tar.gz ?

**Comment by hanneslehmann** [comment]
Hi, sure - it's: [https://github.com/alpinelinux/alpine-make-rootfs](url)

**Comment by hanwen** [comment]
can you make the .tar.gz available? I don't have alpine lying around.

**Comment by rfjakob** [comment]
@hanneslehmann you can attach the file to the github ticket by dragging it into the comment text

**Comment by hanwen** [comment]
I extracted an alpine root image from docker.

https://github.com/hanwen/go-fuse/commit/1abae81d059bc1d18b987b4b2734e47552cc025a for adding the empty directories

https://github.com/hanwen/go-fuse/commit/4e10c985b9605518ff0b9c05f198e7284c4493b3 for access to root.
