### ISSUE TITLE
[v2 API] xfstests generic/011: panic: mode mismatch between readdir 20000 and lookup 40000

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#323]
[v2 API]

The panic is in `fs/bridge.go` and seems hard to trigger on first sight
```go
			if (e.Mode &^ 07777) != (child.stableAttr.Mode &^ 07777) {
				// should go back and change the
				// already serialized entry
				log.Panicf("mode mismatch between readdir %o and lookup %o", e.Mode, child.stableAttr.Mode)
			}
```
But xfstests generic/011 ("dirstress") hits it immediately:
```
fuse-xfstests$ sudo ./check-loopback generic/011
gocryptfs v1.7.1-1-g26f9f8f-dirty; go-fuse v2.0.2-4-g8458b8a; 2019-10-13 go1.12.9 linux/amd64
fuse-xfstests gocryptfs-2018-08-18/182841fe
Sat 19 Oct 2019 11:29:46 PM UTC

/var/tmp/fuse-xfstests/check-loopback/testdir is a mountpoint
FSTYP         -- fuse.loopback
PLATFORM      -- Linux/x86_64 brikett 5.2.17-200.fc30.x86_64
MKFS_OPTIONS  -- /var/tmp/fuse-xfstests/check-loopback/scratchdev
MOUNT_OPTIONS -- -o context=system_u:object_r:root_t:s0 /var/tmp/fuse-xfstests/check-loopback/scratchdev /var/tmp/fuse-xfstests/check-loopback/scratchdir

generic/011 4s ... 01:29:48.608263 mode mismatch between readdir 20000 and lookup 40000
panic: mode mismatch between readdir 20000 and lookup 40000

goroutine 7156 [running]:
log.Panicf(0x56f211, 0x2e, 0xc0000fade8, 0x2, 0x2)
	/usr/local/go/src/log/log.go:345 +0xc0
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).ReadDirPlus(0xc0000b6000, 0xc0003602a0, 0xc000275398, 0xc000342060, 0x0)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fs/bridge.go:907 +0x478
github.com/hanwen/go-fuse/v2/fuse.doReadDirPlus(0xc0000b8000, 0xc000275200)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:175 +0xf6
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0000b8000, 0xc000275200, 0xc000000000)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:470 +0x3ab
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0000b8000, 0xc00027d301)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:437 +0x196
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:304 +0x42b
- output mismatch (see /home/jakob.donotbackup/code/fuse-xfstests/results//generic/011.out.bad)
    --- tests/generic/011.out	2018-01-20 14:29:39.058451927 +0100
    +++ /home/jakob.donotbackup/code/fuse-xfstests/results//generic/011.out.bad	2019-10-20 01:29:48.637660807 +0200
    @@ -2,3 +2,6 @@
     *** TEST 1 -p 1 -n 1 -f <count>
     *** TEST 2 -p 5 -n 1 -f <count>
     *** TEST 3 -p 5 -n 5 -f <count>
    +rm: cannot remove '/var/tmp/fuse-xfstests/check-loopback/testdir/dirstress.12448/stressdir/stress.0': Transport endpoint is not connected
    +rm: cannot remove '/var/tmp/fuse-xfstests/check-loopback/testdir/dirstress.12448/stressdir/stress.2': Transport endpoint is not connected
    +rm: cannot remove '/var/tmp/fuse-xfstests/check-loopback/testdir/dirstress.12448/stressdir/stress.3': Transport endpoint is not connected
    ...
    (Run 'diff -u tests/generic/011.out /home/jakob.donotbackup/code/fuse-xfstests/results//generic/011.out.bad'  to see the entire diff)
Ran: generic/011
Failures: generic/011
Failed 1 of 1 tests

Runtime was 2 seconds, exit code 1
1
```

**Comment by hanwen** [comment]
I think this is another side effect of the underlying FS reusing inodes.

**Comment by rfjakob** [comment]
Yes, I think so too.

This should fix READDIRPLUS: https://review.gerrithub.io/c/hanwen/go-fuse/+/472648 (the newer data wins)
