### ISSUE TITLE
[v2 API] xfstests generic/020: panic: slice bounds out of range [:17] with capacity 0

### ISSUE THREAD

**Issue by rfjakob** [hanwen/go-fuse#337]
```
~/code/fuse-xfstests$ sudo ./check-loopback generic/020
fuse-xfstests gocryptfs-2018-08-18/ab1d77cc
Sat 23 Nov 2019 10:32:50 PM UTC

loopback is /usr/local/bin/loopback
FSTYP         -- fuse.loopback
PLATFORM      -- Linux/x86_64 brikett 5.3.6-200.fc30.x86_64
MKFS_OPTIONS  -- /var/tmp/fuse-xfstests/check-loopback/scratchdev
MOUNT_OPTIONS -- -o context=system_u:object_r:root_t:s0 /var/tmp/fuse-xfstests/check-loopback/scratchdev /var/tmp/fuse-xfstests/check-loopback/scratchdir

generic/020	panic: runtime error: slice bounds out of range [:17] with capacity 0

goroutine 18 [running]:
github.com/hanwen/go-fuse/v2/fuse.doGetXAttr(0xc0000bc000, 0xc000114000)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/opcode.go:277 +0x395
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0000bc000, 0xc000114000, 0xc000000000)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:474 +0x3ab
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0000bc000, 0xc0000f8001)
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:441 +0x196
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
	/home/jakob/go/src/github.com/hanwen/go-fuse/fuse/server.go:308 +0x42b
- output mismatch (see /home/jakob.donotbackup/code/fuse-xfstests/results//generic/020.out.bad)
    --- tests/generic/020.out	2018-01-20 14:29:39.060451932 +0100
    +++ /home/jakob.donotbackup/code/fuse-xfstests/results//generic/020.out.bad	2019-11-23 23:32:51.416611468 +0100
    @@ -5,61 +5,36 @@
           !!! error return
     *** list empty file
        *** print attributes
    +getfattr: <TESTFILE>: Software caused connection abort
    +      !!! error return
     *** query non-existant attribute
    -attr_get: No data available
    ...
    (Run 'diff -u tests/generic/020.out /home/jakob.donotbackup/code/fuse-xfstests/results//generic/020.out.bad'  to see the entire diff)
Ran: generic/020
Failures: generic/020
Failed 1 of 1 tests

Runtime was 1 seconds, exit code 1
1
```

**Comment by rfjakob** [comment]
`loopback -debug` log:
```
23:35:26.181709 rx 138: LOOKUP i1 ["attribute_26712"] 16b
23:35:26.181737 tx 138:     2=no such file or directory, {i0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 B0*0 i0:0 A 0.000000 M 0.000000 C 0.000000}}
23:35:26.181793 rx 140: CREATE i1 {0100644 [WRONLY,NONBLOCK,CREAT,0x8000] (022)} ["attribute_26712"] 16b
23:35:26.181868 tx 140:     OK, {i2761348 g1 {M0100644 SZ=0 L=1 0:0 B0*4096 i0:2761348 A 1574548526.180045 M 1574548526.180045 C 1574548526.180045} &{1 0 0}}
23:35:26.181901 rx 142: FLUSH i2761348 {Fh 1} 
23:35:26.181915 tx 142:     OK
23:35:26.181935 rx 144: SETATTR i2761348 {atime 1574548526.180045087, mtime 1574548526.180045087} 
23:35:26.181970 tx 144:     OK, {tA=0s {M0100644 SZ=0 L=1 0:0 B0*4096 i0:2761348 A 1574548526.181942 M 1574548526.181942 C 1574548526.180045}}
23:35:26.182035 rx 146: FLUSH i2761348 {Fh 1} 
23:35:26.182046 tx 146:     OK
23:35:26.182113 rx 148: RELEASE i2761348 {Fh 1 WRONLY,NONBLOCK,0x8000  L0} 
23:35:26.182131 tx 148:     OK
23:35:26.182836 rx 150: GETATTR i2761348 {Fh 0} 
23:35:26.182863 tx 150:     OK, {tA=1s {M0100644 SZ=0 L=1 0:0 B0*4096 i0:2761348 A 1574548526.181942 M 1574548526.181942 C 1574548526.180045}}
23:35:26.182890 rx 152: LISTXATTR i2761348 {sz 0} 
panic: runtime error: slice bounds out of range [:17] with capacity 0
```

The problem is that `syscall.Listxattr` ([manpage](https://manned.org/listxattr.2)) with size 0 is special. It returns the length of data that WOULD BE returned.

**Comment by rfjakob** [comment]
https://review.gerrithub.io/c/hanwen/go-fuse/+/475633

**Comment by rfjakob** [comment]
Thanks @hanwen for adding the test!
