### ISSUE TITLE
Panic on unknown node after NotifyEntry

### ISSUE THREAD

**Issue by pierreis** [hanwen/go-fuse#354]
I regularly get the following  panic from `go-fuse`:

```
2020/04/08 16:38:53 unknown node 10048884762121421891
panic: unknown node 10048884762121421891

goroutine 823 [running]:
log.Panicf(0xb418f5, 0xf, 0xc000d0fdd0, 0x1, 0x1)
        GOROOT/src/log/log.go:358 +0xc0
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).inode(0xc00039a000, 0x8b74cf732b154443, 0x0, 0x0, 0x0)
        external/com_github_hanwen_go_fuse_v2/fs/bridge.go:227 +0x17b
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).OpenDir(0xc00039a000, 0xc0026ac840, 0xc000f58198, 0xc000f58108, 0xc000000000)
        external/com_github_hanwen_go_fuse_v2/fs/bridge.go:772 +0x72
github.com/hanwen/go-fuse/v2/fuse.doOpenDir(0xc00030fce0, 0xc000f58000)
        external/com_github_hanwen_go_fuse_v2/fuse/opcode.go:182 +0x74
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc00030fce0, 0xc000f58000, 0xc000000000)
        external/com_github_hanwen_go_fuse_v2/fuse/server.go:470 +0x3b7
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc00030fce0, 0xc001353501)
        external/com_github_hanwen_go_fuse_v2/fuse/server.go:437 +0x18a
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        external/com_github_hanwen_go_fuse_v2/fuse/server.go:304 +0x417
```

This started to happen after adding a LRU cache in my application, actively sending `NotifyEntry` when an Inode is evicted from the cache.
I assume that evicting a parent folder of a node referenced by a subsequent request may have side effect, but these do not seem to be documented.

Should this happen (I am not sure whether it derives from a normal, expected condition or from a bug in the stack), wouldn't it be more appropriate to respond an error instead of panicking?

This may relate to #334.

**Comment by pierreis** [comment]
This looks a lot like a race condition to me. The problem doesn't seem to be reproduced when `go-fuse` is running in single-threaded mode. Hence, one theory:

Although the kernel guarantees that a node will not be referenced after a `FORGET` message has been sent, it may happen that a forgotten node is referenced by a previous request in the queue, handled by a goroutine scheduled by the runtime to run after the forget.

Would this make sense?

**Comment by rfjakob** [comment]
I think the kernel waits for all requests to be completed before sending a FORGET, that is, only after it receives a response. That should guarantee that all goroutines have finished processing.

**Comment by pierreis** [comment]
If this is the case, it would be interesting to understand which race condition is at work here. My workload makes go-fuse panic within a minute or so with multiple goroutines, but has been working fine for a few hours in single thread mode.

**Comment by pierreis** [comment]
An extract of the debug log seems to confirm the theory:

```
2020/04/09 10:23:26 rx 72017: GETATTR i11972922661925671148 {Fh 4}
2020/04/09 10:23:26 tx 72017:     OK, {tA=1s {M0100644 SZ=199902 L=1 0:0 B0*0 i0:11972922661925671148 A 1586382326.000000 M 1586382326.000000 C 1586382326.000000}}
2020/04/09 10:23:26 rx 72018: FLUSH i11972922661925671148 {Fh 4}
2020/04/09 10:23:26 tx 72018:     OK
2020/04/09 10:23:26 rx 72019: RELEASE i11972922661925671148 {Fh 4 0x8000  L0}
2020/04/09 10:23:26 rx 72021: RELEASEDIR i408811860997008763 {Fh 3 NONBLOCK,DIRECTORY,0x28000  L0}
2020/04/09 10:23:26 tx 72019:     OK
2020/04/09 10:23:26 rx 72020: RELEASEDIR i1489782920959277745 {Fh 6 NONBLOCK,DIRECTORY,0x28000  L0}
2020/04/09 10:23:26 tx 72021:     OK
2020/04/09 10:23:26 tx 72020:     OK
2020/04/09 10:23:26 rx 72023: LOOKUP i8218206828995173969 ["TEST"] 21b
2020/04/09 10:23:26 rx 72022: RELEASEDIR i5382203406692611568 {Fh 2 NONBLOCK,DIRECTORY,0x28000  L0}
2020/04/09 10:23:26 tx 72022:     OK
2020/04/09 10:23:26 tx 0:     NOTIFY_INVAL_ENTRY, {parent i8218206828995173969 sz 20} "TEST"
2020/04/09 10:23:26 Response: ENTRY_NOTIFY: OK
2020/04/09 10:23:26 tx 72023:     OK, {i10048884762121421891 g0 tE=1s tA=1s {M040755 SZ=4096 L=1 0:0 B0*0 i0:10048884762121421891 A 1577810722.000000 M 1577810722.000000 C 1577810722.000000}}
2020/04/09 10:23:26 rx 72024: FORGET i10048884762121421891 {Nlookup=2}
2020/04/09 10:23:26 rx 72025: LOOKUP i8218206828995173969 ["TEST"] 21b
2020/04/09 10:23:26 tx 72025:     OK, {i10048884762121421891 g0 tE=1s tA=1s {M040755 SZ=4096 L=1 0:0 B0*0 i0:10048884762121421891 A 1577810722.000000 M 1577810722.000000 C 1577810722.000000}}
2020/04/09 10:23:26 rx 72026: OPENDIR i10048884762121421891
2020/04/09 10:23:26 unknown node 10048884762121421891
panic: unknown node 10048884762121421891

goroutine 446 [running]:
log.Panicf(0xb418f5, 0xf, 0xc001f45dd0, 0x1, 0x1)
        GOROOT/src/log/log.go:358 +0xc0
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).inode(0xc000190500, 0x8b74cf732b154443, 0x0, 0x0, 0x0)
        external/com_github_hanwen_go_fuse_v2/fs/bridge.go:227 +0x17b
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).OpenDir(0xc000190500, 0xc0011fc000, 0xc00085d818, 0xc00085d788, 0x0)
        external/com_github_hanwen_go_fuse_v2/fs/bridge.go:772 +0x72
github.com/hanwen/go-fuse/v2/fuse.doOpenDir(0xc0001ad4a0, 0xc00085d680)
        external/com_github_hanwen_go_fuse_v2/fuse/opcode.go:182 +0x74
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0001ad4a0, 0xc00085d680, 0xc000000000)
        external/com_github_hanwen_go_fuse_v2/fuse/server.go:470 +0x3b7
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0001ad4a0, 0xc001f6f001)
        external/com_github_hanwen_go_fuse_v2/fuse/server.go:437 +0x18a
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        external/com_github_hanwen_go_fuse_v2/fuse/server.go:304 +0x417
```

According to this, `go-fuse` is still processing an `opendir` request after the forget has been received.

**Comment by pierreis** [comment]
Using automatic inodes seems to prevent the issue from occurring as well.

**Comment by hanwen** [comment]
the line numbers don't make sense. What version are you using?

**Comment by pierreis** [comment]
Release 2.0.2.
Built with Bazel, not sure whether it does some magic tricks with the go files.

**Comment by hanwen** [comment]
I think may have been fixed in 68f705279531984f44e476496a989888d6d1e6e5

**Comment by pierreis** [comment]
Interesting. Let me try with `master` and update this report accordingly.

**Comment by hanwen** [comment]
I pushed a v2.0.3 tag for your convenience.

**Comment by pierreis** [comment]
Thanks Han-Wen. That sounds great.
Indeed, I cannot reproduce the issue on master. Thank you for your time.

Closing the issue.
