### ISSUE TITLE
Why context canceled and how to handle them

### ISSUE THREAD

**Issue by adlternative** [hanwen/go-fuse#452]
In general, FUSE is functioning normally. However, if there are frequent system calls, my filesystem
immediately detects "context canceled".

I print the call stack, it looks like some FUSE operations(Getattr, Lookup, Opendir...) will trigger this cancel signal.

```
ERRO[0184] meet bad error                                error="context canceled"

goroutine 49513 [running]:
runtime/debug.Stack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x19
github.com/adlternative/tinygitfs/pkg/metadata.errno({0x1ae7de0, 0xc0001920b0})
	/Users/adl/repos/tinygitfs/pkg/metadata/redis.go:104 +0x9b
github.com/adlternative/tinygitfs/pkg/metadata.(*RedisMeta).Getattr(0xc0000b2000, {0x1aec180, 0xc004c60b58}, 0xc?)
	/Users/adl/repos/tinygitfs/pkg/metadata/redis.go:247 +0x10d
github.com/adlternative/tinygitfs/pkg/gitfs.(*Node).Lookup(0xc0000d4000, {0x1aec180, 0xc004c60b58}, {0x1f7def0, 0x1}, 0xc0006350c8)
	/Users/adl/repos/tinygitfs/pkg/gitfs/node.go:193 +0x245
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).lookup(0xc0000b86e0?, 0x1?, 0xc0000d4000, {0x1f7def0, 0x1}, 0xc0006350c8)
	/Users/adl/repos/tinygitfs/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:353 +0x187
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).Lookup(0xc0000b86e0, 0xc0007bc2a0, 0xc000635180, {0x1f7def0, 0x1}, 0xc0006350c8)
	/Users/adl/repos/tinygitfs/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:336 +0xb7
github.com/hanwen/go-fuse/v2/fuse.doLookup(0xc000634fc0?, 0xc000634fc0)
	/Users/adl/repos/tinygitfs/vendor/github.com/hanwen/go-fuse/v2/fuse/opcode.go:358 +0x6b
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0000b8840, 0xc000634fc0)
	/Users/adl/repos/tinygitfs/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:518 +0x1f3
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).loop
	/Users/adl/repos/tinygitfs/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:489 +0xf8
```

So I check #375, and it is found that this is most likely caused by INTERRUPT.
The recommended solution inside is: If the program has a rollback process, return EINTR.
Unfortunately, my upper-level program does not have this, e.g. the opendir system call never
checks for EINTR and never calls opendir again.

So what should I do?

**Comment by hanwen** [comment]
It's hard to tell from your report. The interrupt would happen if the process accessing your FUSE mountpoint receives some signal. I don't know why that would happen.

A simple way to handle this is by not passing on the FUSE context onto other callers (in this case redis?). Then the interrupt is simply ignored.
