### ISSUE TITLE
Error when build gocryptfs with 2.4.2 release 

### ISSUE THREAD

**Issue by libor13** [hanwen/go-fuse#497]
I will try to build gocryptfs with last released go-fuse version 2.4.2 using command
_build-without-openssl.bash_

MacOS Big Sur 11.7.8

This is building output:

```
panic: XTIMES (80000000) overlaps with INIT_RESERVED (80000000)

goroutine 1 [running]:
github.com/hanwen/go-fuse/v2/fuse.(*flagNames).set(0x2?, 0x80000000, {0x1240eb5?, 0xffffffffffffffff?})
	github.com/hanwen/go-fuse/v2@v2.4.2/fuse/print.go:124 +0x179
github.com/hanwen/go-fuse/v2/fuse.init.1()
	github.com/hanwen/go-fuse/v2@v2.4.2/fuse/print_darwin.go:12 +0x31
```

**Comment by libor13** [comment]
When I use last committed sources I have got building error:

```
# github.com/hanwen/go-fuse/v2/fs
../../go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.4.2/fs/loopback.go:14:2: could not import github.com/hanwen/go-fuse/v2/internal/renameat (open : no such file or directory)
```
