### ISSUE TITLE
Strategy to customize loopback.go?

### ISSUE THREAD

**Issue by vsoch** [hanwen/go-fuse#535]
Hi! I'm wanting to customize the Open function for the loopback filesystem, but I don't know how to go about it. It uses internal functions so I can't start from scratch  (unless I wanted to verbatim copy all the code, which I do not want) but when I try to do this:

```go
package fs

import (
	"context"
	"fmt"
	"path/filepath"
	"syscall"

	"github.com/hanwen/go-fuse/v2/fs"
)

// We need to implement a custom LoopbackNode Open function
var _ = (fs.NodeOpener)((*CompatLoopbackNode)(nil))

type CompatLoopbackRoot fs.LoopbackRoot
type CompatLoopbackNode fs.LoopbackNode

// NewLoopbackRoot returns a root node for a loopback file system
// This mimics the same function in the parent library but uses
// our custom interface defined below
func NewLoopbackRoot(rootPath string) (fs.InodeEmbedder, error) {
	var st syscall.Stat_t
	err := syscall.Stat(rootPath, &st)
	if err != nil {
		return nil, err
	}

	root := &CompatLoopbackRoot{
		Path: rootPath,
		Dev:  uint64(st.Dev),
	}

	rootNode := root.newNode(nil, "", &st)
	root.RootNode = rootNode
	return rootNode, nil
}

func (r *CompatLoopbackRoot) newNode(parent *fs.Inode, name string, st *syscall.Stat_t) fs.InodeEmbedder {
	return &CompatLoopbackNode{RootData: r}
}

func (n *CompatLoopbackNode) Open(ctx context.Context, flags uint32) (fh fs.FileHandle, fuseFlags uint32, errno syscall.Errno) {
	fmt.Println("CUSTOM OPEN FOR %s with flags %s\n", ctx, flags)
	flags = flags &^ syscall.O_APPEND
	p := n.path()
	f, err := syscall.Open(p, int(flags), 0)
	if err != nil {
		return nil, 0, fs.ToErrno(err)
	}
	lf := fs.NewLoopbackFile(f)
	return lf, 0, 0
}

func (n *CompatLoopbackNode) path() string {
	path := n.Path(n.root())
	return filepath.Join(n.RootData.Path, path)
}

func (n *CompatLoopbackNode) root() *fs.Inode {
	var rootNode *fs.Inode
	if n.RootData.RootNode != nil {
		rootNode = n.RootData.RootNode.EmbeddedInode()
	} else {
		rootNode = n.Root()
	}
	return rootNode
}
```

This function is problematic:

```go
func (r *CompatLoopbackRoot) newNode(parent *fs.Inode, name string, st *syscall.Stat_t) fs.InodeEmbedder {
	return &CompatLoopbackNode{RootData: r}
}
```
Because the r is:

> cannot use r (variable of type *CompatLoopbackRoot) as *"github.com/hanwen/go-fuse/v2/fs".LoopbackRoot value in struct literalcompiler[IncompatibleAssign](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#IncompatibleAssign)

I'm not sure if anyone has done this (it seems like a reasonable thing to do)? but your advice would be appreciated. Thanks!

**Comment by vsoch** [comment]
The first thing I tried is to try and inherit the functions, e.g.,

<details>

```go
package fs

import (
	"context"
	"fmt"
	"path/filepath"
	"syscall"

	"github.com/hanwen/go-fuse/v2/fs"
)

// We need to implement a custom LoopbackNode Open function
var _ = (fs.NodeOpener)((*CompatLoopbackNode)(nil))

type CompatLoopbackRoot fs.LoopbackRoot
type CompatLoopbackNode struct {
	fs.LoopbackNode
	RootData *CompatLoopbackRoot
}

// NewLoopbackRoot returns a root node for a loopback file system
// This mimics the same function in the parent library but uses
// our custom interface defined below
func NewLoopbackRoot(rootPath string) (fs.InodeEmbedder, error) {
	var st syscall.Stat_t
	err := syscall.Stat(rootPath, &st)
	if err != nil {
		return nil, err
	}

	root := &CompatLoopbackRoot{
		Path: rootPath,
		Dev:  uint64(st.Dev),
	}

	rootNode := root.newNode(nil, "", &st)
	root.RootNode = rootNode
	return rootNode, nil
}

func (r *CompatLoopbackRoot) newNode(parent *fs.Inode, name string, st *syscall.Stat_t) fs.InodeEmbedder {
	return &CompatLoopbackNode{RootData: r}
}

func (n *CompatLoopbackNode) Open(ctx context.Context, flags uint32) (fh fs.FileHandle, fuseFlags uint32, errno syscall.Errno) {
	fmt.Println("CUSTOM OPEN FOR %s with flags %s\n", ctx, flags)
	flags = flags &^ syscall.O_APPEND
	p := n.customPath()
	f, err := syscall.Open(p, int(flags), 0)
	if err != nil {
		return nil, 0, fs.ToErrno(err)
	}
	lf := fs.NewLoopbackFile(f)
	return lf, 0, 0
}

func (n *CompatLoopbackNode) customPath() string {
	path := n.Path(n.customRoot())
	return filepath.Join(n.RootData.Path, path)
}

func (n *CompatLoopbackNode) customRoot() *fs.Inode {
	var rootNode *fs.Inode
	if n.RootData.RootNode != nil {
		rootNode = n.RootData.RootNode.EmbeddedInode()
	} else {
		rootNode = n.Root()
	}
	return rootNode
}
```

</details>

That leads to a segfault

```console
(base) vanessa@vanessa-ThinkPad-P14s-Gen-4:~/Desktop/Code/compat-lib$ ./bin/clib-gen --binary /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/lzcat 
⭐️ Compatibility Library Generator (clib-gen)
Preparing to find shared libraries needed for /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/lzcat
liblzma.so.5
ld-linux-x86-64.so.2
ld-linux-x86-64.so.2
libc.so.6
liblzma.so.5
Mount directory /tmp/compat-lib1330230788
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x50b96c]

goroutine 1 [running]:
github.com/compspec/compat-lib/pkg/fs.(*CompatLoopbackNode).github.com/hanwen/go-fuse/v2/fs.embed(0x10?)
        <autogenerated>:1 +0xc
github.com/hanwen/go-fuse/v2/fs.NewNodeFS({0x5a7d10, 0xc000030300}, 0xc0000e3d20)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:309 +0x104
github.com/hanwen/go-fuse/v2/fs.Mount({0xc0000203a0, 0x19}, {0x5a7d10?, 0xc000030300?}, 0x0?)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/mount.go:26 +0xcb
github.com/compspec/compat-lib/pkg/fs.NewCompatFS()
        /home/vanessa/Desktop/Code/compat-lib/pkg/fs/fs.go:127 +0x245
main.main()
        /home/vanessa/Desktop/Code/compat-lib/cmd/gen/gen.go:32 +0x29c
(base) vanessa@vanessa-ThinkPad-P14s-Gen-4:~/Desktop/Code/compat-lib$ make
mkdir -p ./bin
go build -o ./bin/clib-gen cmd/gen/gen.go
(base) vanessa@vanessa-ThinkPad-P14s-Gen-4:~/Desktop/Code/compat-lib$ ./bin/clib-gen --binary /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/lzcat 
⭐️ Compatibility Library Generator (clib-gen)
Preparing to find shared libraries needed for /home/vanessa/Desktop/Code/spack/opt/spack/linux-ubuntu24.04-zen4/gcc-13.2.0/xz-5.4.6-klise22d77jjaoejkucrczlkvnm6f4au/bin/lzcat
ld-linux-x86-64.so.2
ld-linux-x86-64.so.2
liblzma.so.5
liblzma.so.5
libc.so.6
Mount directory /tmp/compat-lib2627922491
callFusermount: executing ["/usr/bin/fusermount3" "/tmp/compat-lib2627922491" "-o" "ro,fsname=/,subtype=loopback,max_read=131072"]
rx 2: INIT n0 {7.39 Ra 131072 ASYNC_READ,POSIX_LOCKS,ATOMIC_O_TRUNC,EXPORT_SUPPORT,BIG_WRITES,DONT_MASK,SPLICE_WRITE,SPLICE_MOVE,SPLICE_READ,FLOCK_LOCKS,IOCTL_DIR,AUTO_INVAL_DATA,READDIRPLUS,READDIRPLUS_AUTO,ASYNC_DIO,WRITEBACK_CACHE,NO_OPEN_SUPPORT,PARALLEL_DIROPS,HANDLE_KILLPRIV,POSIX_ACL,ABORT_ERROR,MAX_PAGES,CACHE_SYMLINKS,NO_OPENDIR_SUPPORT,EXPLICIT_INVAL_DATA,HANDLE_KILLPRIV_V2,SETXATTR_EXT,INIT_EXT,SECURITY_CTX,HAS_INODE_DAX,CREATE_SUPP_GROUP,HAS_EXPIRE_ONLY,DIRECT_IO_ALLOW_MMAP}  p0
tx 2:     OK, {7.28 Ra 131072 ASYNC_READ,BIG_WRITES,READDIRPLUS,NO_OPEN_SUPPORT,PARALLEL_DIROPS,MAX_PAGES,INIT_EXT 0/0 Wr 131072 Tg 0 MaxPages 32 MaxStack 1}
rx 4: LOOKUP n1 [".go-fuse-epoll-hack"] 20b p2649633
tx 4:     OK, {n18446744073709551615 g0 tE=0s tA=0s {M0100644 SZ=0 L=1 0:0 B0*0 i0:18446744073709551615 A 0.000000 M 0.000000 C 0.000000}}
rx 6: OPEN n18446744073709551615 {LARGEFILE}  p2649633
tx 6:     OK, {Fh 18446744073709551615 }
rx 8: POLL n18446744073709551615  p2649633
tx 8:     38=function not implemented
rx 10: FLUSH n18446744073709551615 {Fh 18446744073709551615}  p2649633
tx 10:     OK
rx 12: ACCESS n1 {u=1000 g=1000 r}  p9223
rx 14: RELEASE n18446744073709551615 {Fh 18446744073709551615 LARGEFILE  L0}  p0
tx 14:     OK
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5061b5]

goroutine 21 [running]:
github.com/hanwen/go-fuse/v2/fs.(*LoopbackNode).root(0xc0000aa090?)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/loopback.go:95 +0x15
github.com/hanwen/go-fuse/v2/fs.(*LoopbackNode).path(0xc00018e180)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/loopback.go:105 +0x18
github.com/hanwen/go-fuse/v2/fs.(*LoopbackNode).Getattr(0xc00018e180, {0x5a6dc8?, 0xc000012060?}, {0x0?, 0x0?}, 0xc00002c0e0)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/loopback.go:371 +0x6d
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).getattr(0xc0001b8000, {0x5a6dc8, 0xc000012060}, 0xc00018e180, {0x0?, 0x0}, 0xc00002c0e0)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:569 +0x9b
github.com/hanwen/go-fuse/v2/fs.(*rawBridge).Access(0xc0001b8000, 0xc00002a0c0, 0xc0000a41a0)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/bridge.go:694 +0xf4
github.com/hanwen/go-fuse/v2/fuse.doAccess(0xc0001aa480?, 0xc0000a4008)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fuse/opcode.go:438 +0x2c
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc00017c1a0, 0xc0000a4008)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:560 +0x2f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc00017c1a0, 0x0)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:533 +0x118
github.com/hanwen/go-fuse/v2/fuse.(*Server).Serve(0xc00017c1a0)
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fuse/server.go:428 +0x71
created by github.com/hanwen/go-fuse/v2/fs.Mount in goroutine 1
        /home/vanessa/Desktop/Code/compat-lib/vendor/github.com/hanwen/go-fuse/v2/fs/mount.go:32 +0x12d
```
And for the directory it says the transport is not connected.

**Comment by hanwen** [comment]
```
type CompatLoopbackNode struct {
	fs.LoopbackNode
	RootData *CompatLoopbackRoot
}
```

this doesn´t work b/c the fs.LoopbackNode has a root field which is now not set.

have a look at https://pkg.go.dev/github.com/hanwen/go-fuse/v2/fs#example-package-LoopbackReuse

**Comment by vsoch** [comment]
That worked beautifully! My custom open function was called, and there are no obvious issues with the fs. Thank you so kindly @hanwen !
