### ISSUE TITLE
Panic in init on macOS 15.1.1 build 24B91 with v2.7.0

### ISSUE THREAD

**Issue by creachadair** [hanwen/go-fuse#546]
I started getting a panic at v2.7.0 on darwin/arm64 from https://github.com/hanwen/go-fuse/blob/47a796d4deaf73ec2ef0e3cb33d177b92599e20d/fuse/opcode.go#L759

I have not yet had a chance to bisect it down, but it seems like it may be related to the recent `requestAlloc` changes. When I have some more time, I will try to debug it further. For now I have pinned to v2.6.4 where things still work fine.

For posterity, the output from `log.Panicf`:
```
2024/11/21 08:10:50 request output buffer too small: code 52, sz 288 + 16 &{STATX 0x104e50f70 64 288 {{0 0 0 0 {{0 0} 0} 0} 0 0 0 0 0} {0 0 0 [0 0] {0 0 0 0 0 0 0 0 0 0 0 0 {0 0 0} {0 0 0} {0 0 0} {0 0 0} 0 0 0 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]}} 0 false}                  
panic: request output buffer too small: code 52, sz 288 + 16 &{STATX 0x104e50f70 64 288 {{0 0 0 0 {{0 0} 0} 0} 0 0 0 0 0} {0 0 0 [0 0] {0 0 0 0 0 0 0 0 0 0 0 0 {0 0 0} {0 0 0} {0 0 0} {0 0 0} 0 0 0 0 [0 0 0 0 0 0 0 0 0 0 0 0 0 0]}} 0 false}
                                                                                                                                       
goroutine 1 [running]:                                                                                                                 
log.Panicf({0x105a95a38?, 0x1400031fc68?}, {0x1400031fdc8?, 0x1?, 0x1?})                                                               
        /usr/local/go/current/src/log/log.go:439 +0x64                                                                                 
github.com/hanwen/go-fuse/v2/fuse.init.1()                                                                                             
        <redacted>/go/pkg/mod/github.com/hanwen/go-fuse/v2@v2.7.0/fuse/opcode.go:759 +0x31c4                              

```

**Comment by hanwen** [comment]
https://github.com/hanwen/go-fuse/issues/544

see https://review.gerrithub.io/c/hanwen/go-fuse/+/1204326

**Comment by creachadair** [comment]
That appears to fix it, thanks!

**Comment by hanwen** [comment]
v2.7.1
